name: Deploy Steadfast WebSocket

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Setup SSH Agent
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
          ssh-agent -a $SSH_AUTH_SOCK > /dev/null
          ssh-add - <<< "${{ secrets.SERVER_DEPLOY_KEY }}"
          ssh-add -l -E sha256

      - name: Deploy to server
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
          HOST: ${{ secrets.SERVER_HOST }}
          USER: ${{ secrets.SERVER_USER }}
        run: |
          echo "Attempting to connect to ${USER}@${HOST}..."
          ssh -o StrictHostKeyChecking=no -v ${USER}@${HOST} 'echo "SSH connection successful"'
          scp -o StrictHostKeyChecking=no -r ./* ${USER}@${HOST}:/root/steadfast-websocket/
          ssh -o StrictHostKeyChecking=no ${USER}@${HOST} '
            cd /root/steadfast-websocket &&
            echo "ENV=production" > .env &&
            source venv/bin/activate &&
            pip install -r requirements.txt &&
            
            echo "Checking if steadfast_websocket service is running..." &&
            if sudo systemctl is-active --quiet steadfast_websocket.service; then
              echo "Service is running. Restarting..." &&
              sudo systemctl restart steadfast_websocket.service
            else
              echo "Service is not running. Starting..." &&
              sudo systemctl start steadfast_websocket.service
            fi &&
            
            echo "Reloading Supervisor configuration..." &&
            sudo supervisorctl reread &&
            sudo supervisorctl update &&
            
            echo "Checking if steadfast_websocket process is running..." &&
            if sudo supervisorctl status steadfast_websocket | grep -q "RUNNING"; then
              echo "Process is running. Restarting..." &&
              sudo supervisorctl restart steadfast_websocket
            else
              echo "Process is not running. Starting..." &&
              sudo supervisorctl start steadfast_websocket
            fi
          '
